# Generated by Django 3.2.20 on 2023-10-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
